podAnnotations:
  vault.hashicorp.com/agent-inject-secret-oauth2-proxy.cfg: "foundry/data/frost-wind-terror/config"
  vault.hashicorp.com/agent-inject-template-oauth2-proxy.cfg: |
    {{- with secret "foundry/data/frost-wind-terror/config" -}}
    client_id = "{{ .Data.data.GITHUB_OAUTH2_PROXY_CLIENT_ID }}"
    client_secret = "{{ .Data.data.GITHUB_OAUTH2_PROXY_CLIENT_SECRET }}"
    cookie_secret = "{{ .Data.data.OAUTH2_PROXY_COOKIE_SECRET }}"
    http_address = "0.0.0.0:4180"
    upstreams = [ "file:///dev/null" ]
    email_domains = [ "*" ]
    # provider = "oidc"
    provider = "github"
    reverse_proxy = true
    {{- end -}}

extraEnv:
#  - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
#    value: "https://xmclark.us.auth0.com/"
#  - name: "OAUTH2_PROXY_PROVIDER"
#    value: "oidc"
#  - name: "OAUTH2_PROXY_REDIRECT_URL"
#    value: "https://foundry2.frost-wind-terror.group/oauth2/callback"
#  - name: "OAUTH2_PROXY_UPSTREAMS"
#    value: "http://foundry-vtt.frost-wind-terror.svc.cluster.local"
#  - name: "OAUTH2_PROXY_ISSUER_URL"
#    value: "https://xmclark.us.auth0.com"
  - name: "OAUTH2_PROXY_SILENCE_PING_LOGGING"
    value: "true"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 50Mi

extraArgs: {
  config: "/vault/secrets/oauth2-proxy.cfg"
}

config:
  existingConfig: null
  configFile: null

proxyVarsAsSecrets: false
