podAnnotations:
  vault.hashicorp.com/agent-inject-template-override-config: |
    {{- with secret "foundry/data/frost-wind-terror/config" -}}
    export FOUNDRY_ADMIN_KEY="{{ .Data.data.FOUNDRY_ADMIN_KEY }}"
    export FOUNDRY_AWS_CONFIG="{{ .Data.data.FOUNDRY_AWS_CONFIG }}"
    export FOUNDRY_HOSTNAME="{{ .Data.data.FOUNDRY_HOSTNAME }}"
    export FOUNDRY_LICENSE_KEY="{{ .Data.data.FOUNDRY_LICENSE_KEY }}"
    export FOUNDRY_PASSWORD="{{ .Data.data.FOUNDRY_PASSWORD }}"
    export FOUNDRY_PROXY_PORT="{{ .Data.data.FOUNDRY_PROXY_PORT }}"
    export FOUNDRY_PROXY_SSL="{{ .Data.data.FOUNDRY_PROXY_SSL }}"
    export FOUNDRY_USERNAME="{{ .Data.data.FOUNDRY_USERNAME }}"
    {{- end -}}
