podAnnotations:
  vault.hashicorp.com/agent-inject-secret-oauth2-proxy.cfg: "foundry/data/goldengulp/config"
  vault.hashicorp.com/agent-inject-template-oauth2-proxy.cfg: |
    {{- with secret "foundry/data/goldengulp/config" -}}
    client_id = "{{ .Data.data.OAUTH2_PROXY_CLIENT_ID }}"
    client_secret = "{{ .Data.data.OAUTH2_PROXY_CLIENT_SECRET }}"
    cookie_secret = "{{ .Data.data.OAUTH2_PROXY_COOKIE_SECRET }}"
    http_address = "0.0.0.0:4180"
    upstreams = [ "file:///dev/null" ]
    email_domains = [ "*" ]
    provider = "oidc"
    reverse_proxy = true
    {{- end -}}

extraEnv:
  - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
    value: "https://xmclark.us.auth0.com/"
  - name: "OAUTH2_PROXY_ISSUER_URL"
    value: "https://xmclark.us.auth0.com"
  - name: "OAUTH2_PROXY_SILENCE_PING_LOGGING"
    value: "true"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 50Mi

extraArgs: {
  config: "/vault/secrets/oauth2-proxy.cfg"
}

config:
  existingConfig: null
  configFile: null

proxyVarsAsSecrets: false
