apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: vault-data
spec:
  persistentVolumeClaim:
    claimName: "data-vault-primary-0"
  schedule:
    - every: 10 minutes
      keep: 3
