apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  admin.txt: {{ default "" .Values.foundryvtt.adminKey | b64enc }}

---
{{- if .Values.selfsigned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-signed
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: {{ .Values.selfsigned.cert | b64enc }}
  tls.key: {{ .Values.selfsigned.key | b64enc }}
type: kubernetes.io/tls
{{- end }}

---
{{- if eq .Values.foundryvtt.s3.awsConfig "file" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundry-vtt.fullname" . }}-aws
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-credentials.json: {{ printf "{\"accessKeyId\": \"%s\", \"secretAccessKey\": \"%s\", \"region\": \"%s\" }" .Values.foundryvtt.s3.aws_access_key_id .Values.foundryvtt.s3.aws_secret_access_key .Values.foundryvtt.s3.aws_region | b64enc }}
{{- end }}