apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-certificate
  namespace: ${namespace}
spec:
  secretName: ${secret_name}
  issuerRef:
    name: ${cluster_issuer_ref_name}
    kind: ClusterIssuer
  dnsNames:
    - ${subdomain_name}
